### ISSUE TITLE
IgnoreQueryFilter does not working

### ISSUE THREAD

**Issue by upper-code** [linq2db/linq2db.EntityFrameworkCore#103]
# Hello everyone! I got a problem while migrating from 2.0.5 to 3x versions: "Index was outside the bounds of the array." #

Stacktrace:
at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.TransformExpression(Expression expression, IDataContext dc, DbContext ctx, IModel model)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.TransformExpression(Expression expression, IDataContext dc, DbContext ctx, IModel model)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsDataConnection.ProcessExpression(Expression expression)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.<LinqToDB-Async-IQueryProviderAsync-ExecuteAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

Code example (exception is thrown when isIgnoreQueryFilter = true)
```
        public async Task<int> UpdateQueryable<TEntity>(Expression<Func<TEntity, bool>> predicate,
            Expression<Func<TEntity, TEntity>> setter, bool isIgnoreQueryFilter = false)
            where TEntity : Entity
        {
            var query = _context.Set<TEntity>().AsQueryable();

            if (isIgnoreQueryFilter)
                query = query.IgnoreQueryFilters();

            return await query.UpdateAsync(predicate, setter);
        }
```
Nuget versions:
    "Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.11" 
    "linq2db.EntityFrameworkCore" Version="3.9.2"

Can you help me with a workaround or fix? Thank you in advance!

**Comment by sdanyliv** [comment]
Will check today, thanks for reporting.

**Comment by sdanyliv** [comment]
Already releases In 3.9.3
