### ISSUE TITLE
updateAsync throw exception 

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db.EntityFrameworkCore#13]
````csharp
try
{
    LinqToDBForEFTools.Initialize();
    //更新
    var effectRows = await db.MemberExpand.Where(m => m.MemberCardId == request.MemberCardId)
        .Set(m => m.BabyMonthAge, memberExpand.BabyMonthAge)
        .Set(m => m.RechargeAmount, memberExpand.RechargeAmount)
        .Set(m => m.ReceiveAmount, memberExpand.ReceiveAmount)
        .Set(m => m.ConsumeCoodsBrand, memberExpand.ConsumeCoodsBrand)
        .Set(m => m.ConsumeCoodsCategory, memberExpand.ConsumeCoodsCategory)
        .Set(m => m.TotalStoredConsumeAmount, memberExpand.TotalStoredConsumeAmount)
        .Set(m => m.TotalStoredRechargeAmount, memberExpand.TotalStoredRechargeAmount)
        .Set(m => m.LastConsumeDate, memberExpand.LastConsumeDate)
        .Set(m => m.LastVisitDate, memberExpand.LastVisitDate)
        .Set(m => m.LastUpdateTime, memberExpand.LastUpdateTime)
        .Set(m => m.TotalConsumeAmount, memberExpand.TotalConsumeAmount)
        .Set(m => m.TotalConsumeOrder, memberExpand.TotalConsumeOrder)
        .Set(m => m.CustomerPrice, memberExpand.CustomerPrice)
        .UpdateAsync(cancellationToken);
    _logger.LogInformation($"更新会员扩展表受影响行数：{effectRows}");
}
catch (Exception e)
{
    _logger.LogError(e, $"会员扩展表{oper}失败");
    return false;
}
````
````csharp
 System.ArgumentException: Parameter 'expression' is a 'LinqToDB.Linq.IUpdatable`1[Hyw.Data.MemberExpand]', which cannot be assigned to type 'System.Collections.Generic.IEnumerable`1[Hyw.Data.MemberExpand]'.
Parameter name: expression
   at Remotion.Utilities.ArgumentUtility.CheckTypeIsAssignableFrom(String argumentName, Type actualType, Type expectedType)
   at Remotion.Linq.QueryableBase`1..ctor(IQueryProvider provider, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.CreateQuery[TElement](Expression expression)
   at LinqToDB.LinqExtensions.Set[T,TV](IQueryable`1 source, Expression`1 extract, TV value) in C:\projects\linq2db\Source\LinqToDB\LinqExtensions.cs:line 877
   at Hyw.CommandHandlers.MemberExpandCreateOrUpdateCommandHandler.Handle(MemberExpandCreateOrUpdateCommand request, CancellationToken cancellationToken) in D:\VsProjects\Hyw2\src\Hyw.CommandHanders\MemberExpandCreateOrUpdateCommandHandler.cs:line 165|url: |action: 
2018-12-06 15:45:53.1325||INFO|Hyw.CommandHandlers.MemberExpandCreateOrUpdateCommandHandler|会员扩展表,操作：更新， DATA:{"ExpandId":0,"MemberCardId":"0115202151325","StarScore":0.0,"TotalConsumeAmount":68.0000,"TotalConsumeOrder":2.0,"CustomerPrice":34.0000,"OrderSalesAmount":68.0000,"RechargeAmount":0.0,"ReceiveAmount":0.0,"TotalStoredRechargeAmount":0.0,"TotalStoredConsumeAmount":0.0,"LastConsumeDate":"2018-08-20T16:01:28","LastVisitDate":"0001-01-01T00:00:00","CreateTime":"2018-12-06T15:45:53.1325086+08:00","LastUpdateTime":"2018-12-06T15:45:53.1325115+08:00","LastUpdateRemark":"","ConsumeCoodsBrand":"d2,PP","ConsumeCoodsCategory":"零食-果仙多维,注册会员,用品类","BabyMonthAge":27} |url: |action: 
````
Where did I write wrong?

**Comment by sdanyliv** [comment]
@quan01994, it is reproducible with non async version? Just `.Update()`

**Comment by quan01994** [comment]
yes,
````csharp
2018-12-06 16:10:36.9099||ERROR|Hyw.CommandHandlers.MemberExpandCreateOrUpdateCommandHandler|会员扩展表更新失败 System.ArgumentException: Parameter 'expression' is a 'LinqToDB.Linq.IUpdatable`1[Hyw.Data.MemberExpand]', which cannot be assigned to type 'System.Collections.Generic.IEnumerable`1[Hyw.Data.MemberExpand]'.
Parameter name: expression
   at Remotion.Utilities.ArgumentUtility.CheckTypeIsAssignableFrom(String argumentName, Type actualType, Type expectedType)
   at Remotion.Linq.QueryableBase`1..ctor(IQueryProvider provider, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.CreateQuery[TElement](Expression expression)
   at LinqToDB.LinqExtensions.Set[T,TV](IQueryable`1 source, Expression`1 extract, TV value) in C:\projects\linq2db\Source\LinqToDB\LinqExtensions.cs:line 877
   at Hyw.CommandHandlers.MemberExpandCreateOrUpdateCommandHandler.Handle(MemberExpandCreateOrUpdateCommand request, CancellationToken cancellationToken) in D:\VsProjects\Hyw2\src\Hyw.CommandHanders\MemberExpandCreateOrUpdateCommandHandler.cs:line 170|url: |action: 
````
but i use this code ,it's run 
````csharp
  var effectRows = await db.MemberExpand.AsQueryable().Where(m => m.MemberCardId == request.MemberCardId)
                            .UpdateAsync(m => new MemberExpand
                            {
                                BabyMonthAge = memberExpand.BabyMonthAge,
                                RechargeAmount = memberExpand.RechargeAmount,
                                ReceiveAmount = memberExpand.ReceiveAmount,
                                ConsumeCoodsBrand = memberExpand.ConsumeCoodsBrand,
                                ConsumeCoodsCategory = memberExpand.ConsumeCoodsCategory,
                                TotalStoredConsumeAmount = memberExpand.TotalStoredConsumeAmount,
                                TotalStoredRechargeAmount = memberExpand.TotalStoredRechargeAmount,
                                OrderSalesAmount = memberExpand.OrderSalesAmount,
                                LastConsumeDate = memberExpand.LastConsumeDate,
                                LastVisitDate = memberExpand.LastVisitDate,
                                LastUpdateTime = DateTime.Now,
                                TotalConsumeAmount = memberExpand.TotalConsumeAmount,
                                TotalConsumeOrder = memberExpand.TotalConsumeOrder,
                                CustomerPrice = memberExpand.CustomerPrice,
                            }, cancellationToken);
````

**Comment by sdanyliv** [comment]
@quan01994, please post `MemberExpand` class, i’ll try to reproduce.

**Comment by quan01994** [comment]
````csharp
 public partial class MemberExpand
    {
        public int ExpandId { get; set; }
        public string MemberCardId { get; set; }
        public decimal StarScore { get; set; }
        public decimal TotalConsumeAmount { get; set; }
        public decimal TotalConsumeOrder { get; set; }
        public decimal CustomerPrice { get; set; }
        public decimal OrderSalesAmount { get; set; }
        public decimal RechargeAmount { get; set; }
        public decimal ReceiveAmount { get; set; }
        public decimal TotalStoredRechargeAmount { get; set; }
        public decimal TotalStoredConsumeAmount { get; set; }
        public DateTime LastConsumeDate { get; set; }
        public DateTime LastVisitDate { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public string LastUpdateRemark { get; set; }
        public string ConsumeCoodsBrand { get; set; }
        public string ConsumeCoodsCategory { get; set; }
        public int BabyMonthAge { get; set; }
    }
````
````csharp
using (var db = new HYWCRMContext(conn))
{
    //判断是否存在
    var flag = await db.MemberExpand.AnyAsync(m => m.MemberCardId == request.MemberCardId, cancellationToken);
    //寄存
    var rechargeOrdersQry = from mtrod in db.MemberTendRechargeOrderDetails
                            from mtro in db.MemberTendRechargeOrder.LeftJoin(m => m.RechargeNo == mtrod.RechargeNo)
                            from gi in db.GoodsInfo.LeftJoin(m => m.GoodsCode == mtrod.GoodsCode)
                            where mtro.MemberCardId == request.MemberCardId && mtrod.Status == 0 && mtro.Status == 0
                            select new
                            {
                                mtro.RechargeDate,
                                mtrod.RechargeNo,
                                mtrod.RechargeAmount,
                                gi.GoodsCode,
                                gi.GoodsBrandCode,
                                gi.GoodsCategoryCode,
                            };
    var rechargeOrders = await rechargeOrdersQry.ToListAsyncLinqToDB(cancellationToken);
    var rechargeAmount = rechargeOrders.Sum(m => m.RechargeAmount);
    //领取
    var receiveOrdersQry = from mtcd in db.MemberTendConsumeDetails
                            from gi in db.GoodsInfo.LeftJoin(m => m.GoodsCode == mtcd.GoodsCode)
                            where mtcd.MemberCardId == request.MemberCardId && mtcd.Status == 0
                            select new
                            {
                                mtcd.ConsumeNo,
                                mtcd.SalePrice,
                                mtcd.ConsumeQty,
                                gi.GoodsCode,
                                gi.GoodsBrandCode,
                                gi.GoodsCategoryCode,
                            };
    var receiveOrders = await receiveOrdersQry.ToListAsyncLinqToDB(cancellationToken);
    var receiveAmount = receiveOrders.Sum(m => m.SalePrice * m.ConsumeQty);
    //流水
    var flowOrdersQry = from oi in db.OrderInfo.AsQueryable()
                        from gi in db.GoodsInfo.LeftJoin(m => m.GoodsCode == oi.GoodsCode)
                        where oi.MemberCardId == request.MemberCardId && oi.OrderStatus == 0
                        select new
                        {
                            oi.OrderNo,
                            oi.SaleMoney,
                            oi.SaleDate,
                            gi.GoodsCode,
                            gi.GoodsBrandCode,
                            gi.GoodsCategoryCode,
                        };
    var flowOrders = await flowOrdersQry.ToListAsyncLinqToDB(cancellationToken);
    var orderSalesAmount = flowOrders.Sum(m => m.SaleMoney);

    //会员储值信息
    var memberStored = await db.MemberStoredFlow
        .Where(m => m.MemberCardId == request.MemberCardId)
        .GroupBy(m => m.MemberCardId)
        .Select(m => new
        {
            TotalStoredRechargeAmount = m.Sum(t => t.BusinessType == "4" ? t.ConsumeAmount : 0),
            TotalStoredConsumeAmount = m.Sum(t => t.BusinessType == "5" ? t.ConsumeAmount : 0)
        }).SingleOrDefaultAsyncLinqToDB(cancellationToken);

    //所有的消费品牌
    var consumeCoodsBrandCodes = flowOrders.Select(m => m.GoodsBrandCode)
            .Union(receiveOrders.Select(m => m.GoodsBrandCode))
            .Union(rechargeOrders.Select(m => m.GoodsBrandCode))
            .Distinct().ToList();

    var consumeCoodsBrands = await db.GoodsBrand.Where(m => consumeCoodsBrandCodes.Contains(m.BrandCode))
        .Select(m => m.BrandCode).ToListAsync(cancellationToken);

    //所有的消费类别
    var consumeCoodsCategoryCodes = flowOrders.Select(m => m.GoodsCategoryCode)
        .Union(receiveOrders.Select(m => m.GoodsCategoryCode))
        .Union(rechargeOrders.Select(m => m.GoodsCategoryCode))
        .Distinct().ToList(); ;

    var consumeCoodsCategories = await db.GoodsCategory.Where(m => consumeCoodsCategoryCodes.Contains(m.Gccode))
        .Select(m => m.Gcname).ToListAsync(cancellationToken);
    var consumeDates = flowOrders.Select(m => m.SaleDate).Union(rechargeOrders.Select(m => m.RechargeDate))
        .ToList();
    //最后消费时间
    var lastConsumeDate = SqlDateTime.MinValue.Value; ; //最后消费时间
    if (consumeDates.Count > 0)
    {
        lastConsumeDate = consumeDates.Max();
    }
    //最后回访时间
    var lastVisitDateQry = from mr in db.MemberRemark.AsQueryable()
                            where mr.RemarkStatus == 0 && mr.MemberId == request.MemberId
                            select Sql.Ext.Max(mr.CreateTime).ToValue();
    var lastVisitDate = await lastVisitDateQry.SingleOrDefaultAsyncLinqToDB(cancellationToken);
    if (lastVisitDate == DateTime.MinValue)
    {
        lastVisitDate = SqlDateTime.MinValue.Value;
    }
    //总消费金额 流水+寄存-领取
    var totalConsumeAmount = orderSalesAmount + rechargeAmount - receiveAmount;
    //总的订单数
    var totalConsumeOrder = flowOrders.Select(m => m.OrderNo).Distinct().Count() +
                            rechargeOrders.Select(m => m.RechargeNo).Distinct().Count() -
                            receiveOrders.Select(m => m.ConsumeNo).Distinct().Count();
    //客单价
    var customerPrice = totalConsumeOrder != 0 ? totalConsumeAmount / totalConsumeOrder : 0;
    var memberExpand = new MemberExpand
    {
        BabyMonthAge = request.BabyMonthAge ?? 0,
        CreateTime = DateTime.Now,
        MemberCardId = request.MemberCardId,
        StarScore = 0m,
        RechargeAmount = rechargeAmount,
        ReceiveAmount = receiveAmount,
        ConsumeCoodsBrand = string.Join(",", consumeCoodsBrands),
        ConsumeCoodsCategory = string.Join(",", consumeCoodsCategories),
        TotalStoredConsumeAmount = memberStored?.TotalStoredConsumeAmount ?? 0m,
        TotalStoredRechargeAmount = memberStored?.TotalStoredRechargeAmount ?? 0m,
        OrderSalesAmount = orderSalesAmount,
        LastConsumeDate = lastConsumeDate,
        LastVisitDate = lastVisitDate,
        LastUpdateTime = DateTime.Now,
        LastUpdateRemark = string.Empty,
        TotalConsumeAmount = totalConsumeAmount,
        TotalConsumeOrder = totalConsumeOrder,
        CustomerPrice = customerPrice,
    };
    var oper = flag ? "更新" : "新增";
    _logger.LogInformation($"会员扩展表,操作：{oper}， DATA:{JsonConvert.SerializeObject(memberExpand)}");
    //更新
    if (flag)
    {
        //只更新当前记录
        try
        {
            LinqToDBForEFTools.Initialize();
            //更新
            var effectRows = await db.MemberExpand.AsQueryable().Where(m => m.MemberCardId == request.MemberCardId)
                .UpdateAsync(m => new MemberExpand
                {
                    BabyMonthAge = memberExpand.BabyMonthAge,
                    RechargeAmount = memberExpand.RechargeAmount,
                    ReceiveAmount = memberExpand.ReceiveAmount,
                    ConsumeCoodsBrand = memberExpand.ConsumeCoodsBrand,
                    ConsumeCoodsCategory = memberExpand.ConsumeCoodsCategory,
                    TotalStoredConsumeAmount = memberExpand.TotalStoredConsumeAmount,
                    TotalStoredRechargeAmount = memberExpand.TotalStoredRechargeAmount,
                    OrderSalesAmount = memberExpand.OrderSalesAmount,
                    LastConsumeDate = memberExpand.LastConsumeDate,
                    LastVisitDate = memberExpand.LastVisitDate,
                    LastUpdateTime = DateTime.Now,
                    TotalConsumeAmount = memberExpand.TotalConsumeAmount,
                    TotalConsumeOrder = memberExpand.TotalConsumeOrder,
                    CustomerPrice = memberExpand.CustomerPrice,
                }, cancellationToken);
            _logger.LogInformation($"更新会员扩展表受影响行数：{effectRows}");
        }
        catch (Exception e)
        {
            _logger.LogError(e, $"会员扩展表{oper}失败");
            return false;
        }
    }
    else
    {
        db.Add(memberExpand);
        try
        {
            await db.SaveChangesAsync(cancellationToken);
        }
        catch (Exception e)
        {
            _logger.LogError(e, $"会员扩展表{oper}失败");
            return false;
        }
    }
    _logger.LogInformation($"更新会员扩展表成功。MemberCardId：{request.MemberCardId}");
    return true;
}
}
````

**Comment by sdanyliv** [comment]
Oh, i see something strange here. Remotion Linq should be not involved in this case.

**Comment by sdanyliv** [comment]
@quan01994 i confirm bug. It is because Remotion Linq is trying to analyse ExpressionTree even before final parsing. I've added fix to `linq2db` which will be available next Thursday.

As workaround just call `ToLinqToDB()` before `Set()`
```cs
    var effectRows = await db.MemberExpand.Where(m => m.MemberCardId == request.MemberCardId)
        .ToLinqToDB()
        .Set(m => m.BabyMonthAge, memberExpand.BabyMonthAge)
...
        .Set(m => m.CustomerPrice, memberExpand.CustomerPrice)
        .UpdateAsync(cancellationToken);
```

**Comment by quan01994** [comment]
ok, thank you. :)

**Comment by sdanyliv** [comment]
Willbe delivered with the next linq2db release.
