### ISSUE TITLE
How can I get the maximum value for every hour

### ISSUE THREAD

**Issue by ingezone** [linq2db/linq2db.EntityFrameworkCore#130]
Hi Svyatoslav, 

Can you help me solve my next problem...

I have a table that records data daily every 15 minutes, based on this frequency, I would have a total of 97 records per day.
(NOTE: The above is for testing purposes only, the actual table will have samples every 3 minutes and in total there will be 480 records per day.)
From the source table I need to create a query that retrieves all the rows that meet the following condition (criteria) for each day:
- For each period of one hour, obtain the row with the highest value in the Datetime Column.

SOURCE TABLE: for each day.
```
+-------+---------------+-----------------------+--------+--------+
|   Id  |  Accumulated  |  	Datetime	| CoordE | CoordN |
+-------+---------------+-----------------------+--------+--------+
|   1	|     	0	|  2021-04-05 00:00:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|   2	|     	15	|  2021-04-05 00:15:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|   3	|     	25	|  2021-04-05 00:30:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|   4	|     	25	|  2021-04-05 00:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|   5	|     	40	|  2021-04-05 01:00:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|   6	|     	55	|  2021-04-05 01:15:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
    :		:	            :		     :        :
    :		:	            :		     :        :
+-------+---------------+-----------------------+--------+--------+
|  93	|     	25	|  2021-04-05 23:00:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|  94	|     	25	|  2021-04-05 23:15:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|  95	|     	40	|  2021-04-05 23:30:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|  96	|     	55	|  2021-04-05 23:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|  97	|     	60	|  2021-04-06 00:00:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
```

NEW TABLE: Response Filtered by DateTime.
```
+-------+---------------+-----------------------+--------+--------+
|   Id  |  Accumulated  |  	Datetime	| CoordE | CoordN |
+-------+---------------+-----------------------+--------+--------+
|   1	|     ...	|  2021-04-05 00:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|   8	|     ...	|  2021-04-05 01:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|  12	|     ...	|  2021-04-05 02:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|  16 	|     ...	|  2021-04-05 03:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
    :		:	            :		     :        :
    :		:	            :		     :        :
+-------+---------------+-----------------------+--------+--------+
|  88	|     ...	|  2021-04-05 21:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|  92	|     ...	|  2021-04-05 22:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+
|  96	|     ...	|  2021-04-05 23:45:00	|  22222 |  11111 |
+-------+---------------+-----------------------+--------+--------+

```

I have tried my following code snippet, but I can't get the correct result:

```
var query = SourceTable
			.Where(t => t.Datetime.Year == rtc.Year &&
						t.Datetime.Month == rtc.Month &&
						t.Datetime.Day == rtc.Day &&
						t.Datetime.Hour >= rtc.Hour)
			//.Where(c => c.CoordE == coordEste && c.CoordN == coordNorte)
			.Where(c => c.Datetime >= Convert.ToDateTime(rtc.ToString("yyyy-MM-dd 01:00:00")))
			//.GroupBy(p => p.Datetime)
			.Select(g => new table { Accumulated = g.Accumulated , Datetime = (g.Datetime), CoordE = g.CoordEste, CoordN = g.CoordNorte })
			.ToList(); 
```

**Comment by sdanyliv** [comment]
```cs
var rnQuery = 
	from t in SourceTable
	where t.Datetime.Year == rtc.Year &&
		t.Datetime.Month == rtc.Month &&
		t.Datetime.Day == rtc.Day &&
		t.Datetime.Hour >= rtc.Hour
	select new 
	{
		Source = t,
		RN = Sql.Ext.RowNumber().Over()
			.PartitionBy(t.Datetime.Year, t.Datetime.Month, t.Datetime.Day, t.Datetime.Hour)
			.OrderByDesc(t.Datetime)
			.ToValue()
	}

var result = rnQuery
	.Where(r => r.RN == 1)
	.Select(r => r.Source)
        .ToList();
```

**Comment by ingezone** [comment]
**It does not work, I have the following error**


[<a href='https://postimg.cc/fJ1Pcd56' target='_blank'><img src='https://i.postimg.cc/y8NzzXRY/ddddd.png' border='0' alt='ddddd'/></a>](url)

**Comment by ingezone** [comment]
**To test the code I am using LINQPad 6, this is the test code:**


```
private class cEntity
{
	public Int32 Id { get; set; }
	public double Accumulated { get; set; }
	public DateTime Datetime { get; set; }
	public double CoordEste { get; set; }
	public double CoordNorte { get; set; }
};

void Main()
{
	var listOfDTs = new List<cEntity>();
	listOfDTs.Add(new cEntity { Id = 1, Accumulated = 015, Datetime = DateTime.Parse("2021-04-01 00:15:00"), CoordEste = 1, CoordNorte = 2 });
	listOfDTs.Add(new cEntity { Id = 2, Accumulated = 030, Datetime = DateTime.Parse("2021-04-01 00:30:00"), CoordEste = 1, CoordNorte = 2 });
	listOfDTs.Add(new cEntity { Id = 3, Accumulated = 045, Datetime = DateTime.Parse("2021-04-01 00:45:00"), CoordEste = 1, CoordNorte = 2 });
	listOfDTs.Add(new cEntity { Id = 4, Accumulated = 115, Datetime = DateTime.Parse("2021-04-01 01:00:00"), CoordEste = 1, CoordNorte = 2 });
	listOfDTs.Add(new cEntity { Id = 5, Accumulated = 125, Datetime = DateTime.Parse("2021-04-01 01:15:00"), CoordEste = 1, CoordNorte = 2 });
	listOfDTs.Add(new cEntity { Id = 6, Accumulated = 135, Datetime = DateTime.Parse("2021-04-01 01:30:00"), CoordEste = 1, CoordNorte = 2 });
	listOfDTs.Add(new cEntity { Id = 7, Accumulated = 145, Datetime = DateTime.Parse("2021-04-01 01:45:00"), CoordEste = 1, CoordNorte = 2 });
	listOfDTs.Add(new cEntity { Id = 8, Accumulated = 155, Datetime = DateTime.Parse("2021-04-01 02:00:00"), CoordEste = 1, CoordNorte = 2 });
	listOfDTs.Add(new cEntity { Id = 9, Accumulated = 165, Datetime = DateTime.Parse("2021-04-01 02:15:00"), CoordEste = 1, CoordNorte = 2 });
	string json = JsonConvert.SerializeObject(listOfDTs);
	var jsonList = JsonConvert.DeserializeObject<List<cEntity>>(json).ToList();
	var rtc = DateTime.Parse("2021-04-01 00:00:00"); var cordEste = 1; var cordNorte = 2;
	var rnQuery = from t in jsonList
				  where t.Datetime.Year == rtc.Year &&
						t.Datetime.Month == rtc.Month &&
						t.Datetime.Day == rtc.Day &&
						t.Datetime.Hour >= rtc.Hour
				  select new
				  {
					 Source = t,
					  RN = Sql.Ext.RowNumber().Over()
						  .PartitionBy(t.Datetime.Year, t.Datetime.Month, t.Datetime.Day, t.Datetime.Hour)
						  .OrderByDesc(t.Datetime)
						  .ToValue()
				  };
	//rnQuery.Dump();
	//var result = rnQuery
	//	.Where(r => r.RN == 1)
	//	.Select(r => r.Source)
	//		.ToList();
	rnQuery.Dump();
}

```

**Comment by sdanyliv** [comment]
This query is not for IEnumerable but for linq2db IQueryable.

**Comment by ingezone** [comment]
Update the query...
But now it gives me the following error:

```
InvalidOperationException
An exception was thrown while attempting to evaluate the LINQ query parameter expression 'Sql.Ext.RowNumber().Over()'.


TargetSite
RuntimeMethodInfo:  ParameterExtractingExpressionVisitor.GetValue (Expression expression, String& parameterName) | 
```




--



--



--

**Comment by sdanyliv** [comment]
Probably you have missed `ToLinqToDB()` call, Without that linq2db cannot intercept query.

**Comment by ingezone** [comment]
Finally I got it to work, but doing the query directly to the MySQL database using EF (dbContext).

However, I shouldn't use (dbContext), I just need to use a `LIST<T>`.




```
using (var db = new db_pozosContext())
{
                    var rnQuery = from t in db.PdhAccumulateds
                                              where t.DateTime.Year == rtc.Year
                                              && t.DateTime.Month == rtc.Month
                                              && t.DateTime.Day == rtc.Day                                                                                         
                                              select new 
                                              {
                                                  Source = t,
                                                  RN = Sql.Ext.RowNumber().Over()
                                                        .PartitionBy(t.DateTime.Year, t.DateTime.Month, t.DateTime.Day, t.DateTime.Hour)
                                                        .OrderByDesc(t.DateTime)
                                                        .ToValue()
                                              };
                    foreach (var item in rnQuery.ToLinqToDB())
                    {
                        //Console.WriteLine($"{item.RN}  {item.Source.Accumulated} {item.Source.DateTime} ");
                    }
                    var result = rnQuery
                                 .Where(r => r.RN == 1)
                                 .Select(r => r.Source)
                            	 .ToLinqToDB().ToList();
                    foreach (var item in result)
                    {
                        Console.WriteLine($"Id: {item.Id}  Accumulated: {item.Accumulated}  FechaTotalizado: {item.DateTime} ");
                    }                    
 }
```

**Comment by ingezone** [comment]
What should I do to be able to read from a LIST <T>, I have tried everything and I cannot get the following code to work.

Please can you help to solve my problem?


```

List<xdhAccumulated> listOfDTs = new();
listOfDTs.Add(new xdhAccumulated { Accumulated = 015, DeteTime = DateTime.Parse("2021-04-01 00:15:00"), CoordEste = 1, CoordNorte = 2 });
listOfDTs.Add(new xdhAccumulated { Accumulated = 030, DeteTime = DateTime.Parse("2021-04-01 00:30:00"), CoordEste = 1, CoordNorte = 2 });
listOfDTs.Add(new xdhAccumulated { Accumulated = 045, DeteTime = DateTime.Parse("2021-04-01 00:45:00"), CoordEste = 1, CoordNorte = 2 });
listOfDTs.Add(new xdhAccumulated { Accumulated = 115, DeteTime = DateTime.Parse("2021-04-01 01:00:00"), CoordEste = 1, CoordNorte = 2 });
listOfDTs.Add(new xdhAccumulated { Accumulated = 125, DeteTime = DateTime.Parse("2021-04-01 01:15:00"), CoordEste = 1, CoordNorte = 2 });
listOfDTs.Add(new xdhAccumulated { Accumulated = 135, DeteTime = DateTime.Parse("2021-04-01 01:30:00"), CoordEste = 1, CoordNorte = 2 });
listOfDTs.Add(new xdhAccumulated { Accumulated = 145, DeteTime = DateTime.Parse("2021-04-01 01:45:00"), CoordEste = 1, CoordNorte = 2 });
listOfDTs.Add(new xdhAccumulated { Accumulated = 155, DeteTime = DateTime.Parse("2021-04-01 02:00:00"), CoordEste = 1, CoordNorte = 2 });
listOfDTs.Add(new xdhAccumulated { Accumulated = 165, DeteTime = DateTime.Parse("2021-04-01 02:15:00"), CoordEste = 1, CoordNorte = 2 });

var xxx = listOfDTs.AsQueryable().ToLinqToDB();

var rnQuery = from t in xxx
              where t.DeteTime.Year == rtc.Year
              && t.DeteTime.Month == rtc.Month
              && t.DeteTime.Day == rtc.Day
              //select t;
              select new
              {
                   Source = t,
                   RN = Sql.Ext.RowNumber().Over()
                       .PartitionBy(t.DeteTime.Year, t.DeteTime.Month, t.DeteTime.Day, t.DeteTime.Hour)
                       .OrderByDesc(t.DeteTime)
                       .ToValue()
               };
               foreach (var item in rnQuery.ToLinqToDB())
               {
                   Console.WriteLine($"{item.RN}  {item.Source.Totalizador}  {item.Source.FechaTotalizador} ");
               }
```

**Comment by ingezone** [comment]
This is the EXCEPTION when I use my code with `LIST <T>`

```
System.ArgumentException: Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'System.Linq.EnumerableQuery`1[<>f__AnonymousType11`1[WorkerService_TOTALIZADOR.Worker+xdhtotalizador]]'.
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.GetCurrentContext(IQueryable query)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.ToLinqToDB[T](IQueryable`1 query)
```

**Comment by ingezone** [comment]
What am I doing wrong, I can't find the solution.

**Comment by sdanyliv** [comment]
> What am I doing wrong, I can't find the solution.

It is SO question. For `IEnumerable` it will be answered in minutes.

For IEnumebare this code is simple.

```cs
var query = 
	from t in SourceTable
	where t.Datetime.Year == rtc.Year &&
		t.Datetime.Month == rtc.Month &&
		t.Datetime.Day == rtc.Day &&
		t.Datetime.Hour >= rtc.Hour
    group t by new {t.Datetime.Year, t.Datetime.Month, t.Datetime.Day, t.Datetime.Hour} into g
	select g.OrderByDescending(x => x.Datetime).First()

var result = query
    .ToList();
```

**Comment by ingezone** [comment]
Finally now it works as I wanted. :)
I can't believe how easy it was ... Well I was very lost.

**Comment by ingezone** [comment]
How can I make a donation to you?

**Comment by ingezone** [comment]
Hello again.

**How can I do a Bulk Update for the MySQL provider**

Using the result of your previous solution, I can currently make a bulk insert, **But how do I do for a bulk update**?

```
private static async Task RecordAccumulated(List<HTEntity> results, DateTime rtc)
{
	using (var DbContext = new db_Context())
	{                
		if (true)
		{		
		    // Massive INSERT	
		    result = await DbContext.BulkCopyAsync(results);
		    Console.WriteLine(result.RowsCopied);
		}
		else
		{
		    // Massive UPDATE
                   ??????????????????????
		}
	}
}
```

**Comment by sdanyliv** [comment]
Try the following:
```cs
private static async Task RecordAccumulated(List<HTEntity> results, DateTime rtc)
{
    using (var DbContext = new db_Context())
    {                
        if (true)
        {		
            // Massive INSERT	
            result = await DbContext.BulkCopyAsync(results);
            Console.WriteLine(result.RowsCopied);
        }
        else
        {
            // Massive UPDATE
            using var temp = await DbContext.CreateTempTableAsync(results);

            await db.GetTable<HTEntity>()
                .Merge()
                .Using(temp)
                .OnTargetKey()
                .UpdateWhenMatched()
                .MergeAsync();
        }
    }
}
```

**Comment by ingezone** [comment]
How do I correct that problem?

[<a href='https://postimg.cc/hJy2Shj4' target='_blank'><img src='https://i.postimg.cc/gJdQHZbh/im1.png' border='0' alt='im1'/></a>](url)

**Comment by ingezone** [comment]
Once the code is executed, when trying to do a bulk update, it throws the following exception.

```
Exception: 'LinqToDB.LinqToDBException' en System.Private.CoreLib.dll
Method OnTargetKey() needs at least one primary key column
```

**Comment by sdanyliv** [comment]
Sorry missed that your MySQL do not supports merge.
```cs
// Massive UPDATE
using var db = DbContext.CreateLinqToDbConnection();
using var temp = await db.CreateTempTableAsync(datos);

var toUpdate = 
	from d in db.GetTable<HTEntity>()
	from t in temp.InnerJoin(t => t.Id == d.Id)
	select new { d, t };

await toUpdate.UpdateAsync(u => t.d, u => t.t);
```

**Comment by ingezone** [comment]
The following error appeared.



[<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/HxXJhgvW/Error.png' border='0' alt='Error'/></a>](url)

I made the following change to remove the error.

`await toUpdate.UpdateAsync(t => t.d, t => t.t);`

Once the code is executed, it throws the following exception.

```
Exception: 'System.InvalidOperationException' en System.Private.CoreLib.dll
Operation is not valid due to the current state of the object.
```

**Comment by sdanyliv** [comment]
Post your model

**Comment by ingezone** [comment]
db_pozosContext.cs

```
namespace WorkerServiceNET5_PD.Models
{
    public partial class db_pozosContext : DbContext
    {
        public db_pozosContext()
        {
        }

        public db_pozosContext(DbContextOptions<db_pozosContext> options)
            : base(options)
        {
        }
     
        public virtual DbSet<Pdhtotalizador> Pdhtotalizadors { get; set; }       
        public virtual DbSet<Pozo> Pozos { get; set; }      
        public virtual DbSet<Protocolo> Protocolos { get; set; }
        public virtual DbSet<Proveedortelemetrium> Proveedortelemetria { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseMySql("server=localhost;database=db_pozos;uid=root;pwd=", Microsoft.EntityFrameworkCore.ServerVersion.FromString("8.0.20-mysql"));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Pdhtotalizador>(entity =>
            {
                entity.ToTable("pdhtotalizador");

                entity.HasIndex(e => new { e.CoordEste, e.CoordNorte }, "fk_pdht");

                entity.Property(e => e.FechaTotalizador).HasColumnType("datetime");

                entity.HasOne(d => d.Coord)
                    .WithMany(p => p.Pdhtotalizadors)
                    .HasForeignKey(d => new { d.CoordEste, d.CoordNorte })
                    .HasConstraintName("pdhtotalizador_ibfk_1");
            });      

            modelBuilder.Entity<Pozo>(entity =>
            {
                entity.HasKey(e => new { e.CoordEste, e.CoordNorte })
                    .HasName("PRIMARY")
                    .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                entity.ToTable("pozo");

                entity.HasIndex(e => e.CoordEste, "CoordEste");

                entity.HasIndex(e => e.CoordNorte, "CoordNorte");

                entity.HasIndex(e => e.NombreProveedorTelemetria, "FK_PO");

                entity.HasIndex(e => e.NombrePozoAdm, "NombrePozoAdm");

                entity.Property(e => e.CodigoObra)
                    .HasColumnType("varchar(15)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.Property(e => e.DatumZona)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.Property(e => e.Dnsprotocolo)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("DNSProtocolo")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.Property(e => e.EnableSoap).HasColumnName("EnableSOAP");

                entity.Property(e => e.NombrePozo)
                    .HasColumnType("varchar(255)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.Property(e => e.NombrePozoAdm)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.Property(e => e.NombreProveedorTelemetria)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.HasOne(d => d.NombreProveedorTelemetriaNavigation)
                    .WithMany(p => p.Pozos)
                    .HasForeignKey(d => d.NombreProveedorTelemetria)
                    .HasConstraintName("FK_PO");
            });            

            modelBuilder.Entity<Protocolo>(entity =>
            {
                entity.HasKey(e => e.NombreProtocolo)
                    .HasName("PRIMARY");

                entity.ToTable("protocolo");

                entity.Property(e => e.NombreProtocolo)
                    .HasColumnType("varchar(255)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");
            });

            modelBuilder.Entity<Proveedortelemetrium>(entity =>
            {
                entity.HasKey(e => e.NombreProveedorTelemetria)
                    .HasName("PRIMARY");

                entity.ToTable("proveedortelemetria");

                entity.HasIndex(e => e.NombreProtocolo, "FK_PT");

                entity.HasIndex(e => e.NombreProveedorTelemetria, "NombreProveedorTelemetria");

                entity.Property(e => e.NombreProveedorTelemetria)
                    .HasColumnType("varchar(255)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.Property(e => e.ColorMarker)
                    .IsRequired()
                    .HasColumnType("varchar(15)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.Property(e => e.Descripcion)
                    .HasColumnType("longtext")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.Property(e => e.NombreProtocolo)
                    .HasColumnType("varchar(255)")
                    .HasCharSet("latin1")
                    .HasCollation("latin1_swedish_ci");

                entity.HasOne(d => d.NombreProtocoloNavigation)
                    .WithMany(p => p.Proveedortelemetria)
                    .HasForeignKey(d => d.NombreProtocolo)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_PT");
            }); 

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
```

**Comment by ingezone** [comment]
Pdhtotalizador.cs

```
namespace WorkerServiceNET5_PD.Models
{
    public partial class Pdhtotalizador
    {
        public int Id { get; set; }
        public double Totalizador { get; set; }
        public DateTime FechaTotalizador { get; set; }
        public double CoordEste { get; set; }
        public double CoordNorte { get; set; }

        public virtual Pozo Coord { get; set; }
    }
}
```

**Comment by sdanyliv** [comment]
Sorry for delay. Looks like there is  bug in core library. Try this workaround:
```cs
using var temp = await db.CreateTempTableAsync(datos, tableName: typeof(Pdhtotalizador).Name + "_temp", tableOptions: TableOptions.DropIfExists);

var toUpdate = 
	from d in db.GetTable<Pdhtotalizador>()
	from t in temp.InnerJoin(t => t.Id == d.Id)
	select new { d, t };

await toUpdate.UpdateAsync(db.GetTable<Pdhtotalizador>(), u => new Pdhtotalizador()
{
	Totalizador = u.t.Totalizador,
	FechaTotalizador = u.t.FechaTotalizador,
	CoordEste = u.t.CoordEste,
	CoordNorte = u.t.CoordNorte
});
```

**Comment by ingezone** [comment]
`from t in temp.InnerJoin(t => t.Id == d.Id)`

Because the `datos` IDs start from 1 to n, the InnerJoin comparison `(t => t.Id == d.Id)` does not work. The table `<Pdhtotalizador>` has other IDs and they don't match.

I finally made the following change and it worked correctly.

```
var toUpdate = from d in db.GetTable<Pdhtotalizador>()
                                           from t in temp.InnerJoin(t => t.FechaTotalizador.Year == d.FechaTotalizador.Year)
                                                         .InnerJoin(t => t.FechaTotalizador.Month == d.FechaTotalizador.Month)
                                                         .InnerJoin(t => t.FechaTotalizador.Day == d.FechaTotalizador.Day)
                                                         .InnerJoin(t => t.FechaTotalizador.Hour == d.FechaTotalizador.Hour)
                                           select new { d, t };
```
For my case, I need to do the comparison with the date every 1 hour. 
The way to add the other `InnerJoin` is fine?
Or there is a better or more efficient way to do it.

**Comment by sdanyliv** [comment]
Last one is correct. `InnerJoin` should be applied only once to right recordset.

**Comment by MaceWindu** [comment]
Closing as answered
