### ISSUE TITLE
Cannot create temp table with Guid as Id data type when using Sqlite due to `AUTOINCREMENT`

### ISSUE THREAD

**Issue by Nate129** [linq2db/linq2db.EntityFrameworkCore#143]
Hi,

I am attempting to copy entities with a `Guid` entity type into a temporary table in order to do a bulk update. When I call `CreateTempTable` I get the following exception:

```
Exception message: `SQLite Error 1: 'AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY'.`
Stack trace: Microsoft.Data.Sqlite.SqliteException
SQLite Error 1: 'AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass31_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.CreateTable`1.Query(IDataContext dataContext, String tableName, String serverName, String databaseName, String schemaName, String statementHeader, String statementFooter, DefaultNullable defaultNullable, TableOptions tableOptions)
   at LinqToDB.DataExtensions.CreateTable[T](IDataContext dataContext, String tableName, String databaseName, String schemaName, String statementHeader, String statementFooter, DefaultNullable defaultNullable, String serverName, TableOptions tableOptions)
   at LinqToDB.TempTable`1..ctor(IDataContext db, IEnumerable`1 items, BulkCopyOptions options, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions)
   at LinqToDB.DataExtensions.CreateTempTable[T](IDataContext db, IEnumerable`1 items, BulkCopyOptions options, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions)
```

It would seem that linq2db is attempting to use `AUTOINCREMENT` even with `Guid` with Sqlite. Is it possible to configure linq2db to prevent this from being set on the temporary table?

Perhaps is there another way to do a bulk update with a collection of entities in memory to a table without first saving the entities that need to be updated to a temporary table and doing a join? 

### Steps to reproduce
Attempt to bulk copy entities that have the `Guid` Id type into temporary table as below:

```c#
var tempTable = connection.CreateTempTable(people, new BulkCopyOptions {KeepIdentity = true});
```

I have a demo repo created that demonstrates the error in a test [here](https://github.com/Nate129/Linq2dbGuidAutoIncrementDemo).

### Environment details
linq2db version: 3.3.0
Database Server: Sqlite
Database Provider: Microsoft.Data.Sqlite
Operating system: Windows 10
.NET Framework: .NET 5

Thank you!

**Comment by MaceWindu** [comment]
@sdanyliv  looks like Identity flag on non-numeric column set on data model import.

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs#L160

https://github.com/Nate129/Linq2dbGuidAutoIncrementDemo/blob/master/Linq2dbGuidAutoIncrementDemo/EfCoreSqliteInMemoryDbFactory.cs#L67

**Comment by Nate129** [comment]
Hi, 

I see that my factory class's version triggers code was linked, so I'll clarify its purpose just in case it's unclear or misleading. The triggers are meant to increment the version for rows in non-temporary tables when they are added or changed. The version is updated to simulate databases that actually have built in versioning for my tests.

The props variable (which is what fields the triggers are added to) is set as such:

``` c#
var props = table.GetProperties().Where(p =>
            p.ClrType == typeof(byte[]) && p.ValueGenerated == ValueGenerated.OnAddOrUpdate &&
            p.IsConcurrencyToken);
```

The `p.ClrType == typeof(byte[])` type check might pass and the `p.ValueGenerated` check might pass for `Id` when the type is `Guid` but `IsConcurrencyToken` should not pass, so `props` won't contain the Id column, making it irrelevant when dealing with a `Guid` issue on the `Id` column.

The trigger is also only added to "permanent" tables in the context when the context is instantiated, so it shouldn't be involved when creating a temporary table. 

Also, you can disable the addition of the triggers by changing the line in the test where the context is instantiated to: 

``` c#
var context = dbFactory.CreateDbContext<MainDbContext>(false, s => _testOutputHelper.WriteLine(s));
```

and the issue will still occur when running the test.

My apologies if the trigger was misleading, I should have removed it for the demo.

Thanks for looking into this!

**Comment by Nate129** [comment]
Hi, 

Is there a potential workaround I could use to avoid this problem? It's becoming more and more of a blocker for me. 

Thanks.

**Comment by Nate129** [comment]
I'm flattered to see that my test/factory was used :)

Thanks for getting this fixed! Looking forward to the release.
