### ISSUE TITLE
Problems with Left Outer Join

### ISSUE THREAD

**Issue by shishmak** [linq2db/linq2db.EntityFrameworkCore#20]
Hello,

left join not generate with EF context 
exception error:
>  Method 'Boolean IsDBNull(Int32)' declared on type 'System.Data.IDataRecord' cannot be called with instance of type 'System.Boolean'

my model:
```cs
    public partial class Devtypes
    {
        public int Devtypeid { get; set; }
        public string Typename { get; set; }
        public int GlobalType { get; set; }
    }

    public partial class Devices
    {
        public Guid Devid { get; set; }
        public string Sernum { get; set; }
        public int Devtypeid { get; set; }
    }   
```

Context
```cs
public partial class IssueContext : DbContext
 {
        public IssueContext()  {  }
        public IssueContext(DbContextOptions<IssueContext> options)
            : base(options)   {  }

        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Devtypes> Devtypes { get; set; }
}
```

Error code
```cs
using (var l2db = db.CreateLinqToDbConnection())
{
     LinqToDB.Common.Configuration.Linq.GenerateExpressionTest = true;
                    var test =
                        from dt in l2db.GetTable<Devtypes>()
                        from d in l2db.GetTable<Devices>().LeftJoin(pr => pr.Devtypeid == dt.Devtypeid)
                        select new { dt, d }
                           ;

      var x0 = test.ToList();

 }
```

this code throw exception:
```json
{
	"ClassName": "System.ArgumentException",
	"Message": "Method 'Boolean IsDBNull(Int32)' declared on type 'System.Data.IDataRecord' cannot be called with instance of type 'System.Boolean'",
	"StackTraceString": "at System.Linq.Expressions.Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
					   at System.Linq.Expressions.Expression.ValidateStaticOrInstanceMethod(Expression instance, MethodInfo method)
					   at System.Linq.Expressions.Expression.ValidateMethodAndGetParameters(Expression instance, MethodInfo method)
					   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
					   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
					   at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.<>c__DisplayClass6_0.<GetDbFunctionFromMethodCall>b__0(MemberInfo mi)
					   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
					   at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetAttributes[T](Type type, MemberInfo memberInfo, Boolean inherit)
					   at System.Linq.Enumerable.<SelectManyIterator>d__167`3.MoveNext()
					   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
					   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
					   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
					   at LinqToDB.Mapping.MappingSchema.GetAttribute[T](Type type, MemberInfo memberInfo, Boolean inherit)
					   at LinqToDB.Linq.Builder.ExpressionBuilder.UpdateNullabilityFromExtension(Expression resultExpr)
					   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
					   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
					   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
					   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
					   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass77_0.<BuildExpression>b__0(Expression expr)
					   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
					   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
					   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
					   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
					   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
					   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
					   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
					   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
					   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
					   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
					   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)",
	"RemoteStackIndex": 0,
	"HResult": -2147024809,
	"Source": "System.Linq.Expressions",
}
```
this error only appears when I use "linq2db.EntityFrameworkCore"
in linq2db with this model I got normal left join qwery
I try both Guids and Integers as primary, error is same

my enviroment:
Asp Net Core 2.2
"linq2db" Version="2.9.1" 
"linq2db.EntityFrameworkCore" Version="1.7.0"
"Npgsql" Version="4.1.1" 
"Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.2.4"
Postgres 9.6

**Comment by sdanyliv** [comment]
Thanks for reporting. Will fix that soon.

**Comment by sdanyliv** [comment]
I need `Devtypes` and `Devices` definition and how you configure context for these types.

**Comment by shishmak** [comment]
I tried with fluent api and with atributes, error appeared on both way
EFContext configure as usially (with options in DI in startup)

**Comment by sdanyliv** [comment]
@shishmak, please if you can.

**Comment by sdanyliv** [comment]
I can not reproduce in 1.7 either. So it is better to create simple project to reproduce.

**Comment by shishmak** [comment]
https://github.com/shishmak/Linq2db.TestProjs
this is repository link. try proj TestLinq2DbAspCore (use launch profile TestLinq2DbAspCore to open console)
p.s. sorry for a lot of garbage in other projects, I use this code for various tests on using linq2db

**Comment by shishmak** [comment]
@sdanyliv Hello, Did you try my project?

**Comment by sdanyliv** [comment]
Sorry, not yet. I’m a little bit busy this week. Will check in a couple days.

**Comment by shishmak** [comment]
@sdanyliv, Thanks for your answer. I look forward to your results :)

**Comment by sdanyliv** [comment]
@shishmak, I have reproduced bug. Unfortunately it is related to linq2db code. So fix will be released with next linq2db version.
PR to track: https://github.com/linq2db/linq2db/pull/1955
