### ISSUE TITLE
Compatible with 4.2.0

### ISSUE THREAD

**Issue by darkflame0** [linq2db/linq2db.EntityFrameworkCore#248]
error now:
```
System.TypeLoadException:“Could not load type 'LinqToDB.Expressions.Extensions' from assembly 'linq2db, Version=4.2.0.0, Culture=neutral, PublicKeyToken=e41013125f9e410a'.”
```

**Comment by sdanyliv** [comment]
Just released new version.

**Comment by darkflame0** [comment]
@sdanyliv same issue in 4.3.0

```
      System.TypeLoadException: Could not load type 'LinqToDB.Expressions.ExpressionExtensions' from assembly 'linq2db, Version=4.3.0.0, Culture=neutral, PublicKeyToken=e41013125f9e410a'.
         at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetAttributes[T](Type type, Boolean inherit)
         at LinqToDB.Mapping.MappingSchema.GetAttributes[T](Type type, Boolean inherit)
         at LinqToDB.Mapping.MappingSchema.GetAttributes[T](Type type, Func`2 configGetter, Boolean inherit, Boolean exactForConfiguration)
         at LinqToDB.Mapping.MappingSchema.GetAttribute[T](Type type, Func`2 configGetter, Boolean inherit)
         at LinqToDB.Mapping.EntityDescriptor.Init()
         at LinqToDB.Mapping.EntityDescriptor..ctor(MappingSchema mappingSchema, Type type)
         at LinqToDB.Mapping.MappingSchema.<>c.<GetEntityDescriptor>b__98_0(ICacheEntry`1 o, MappingSchema context)
         at LinqToDB.Common.Internal.Cache.CacheExtensions.GetOrCreate[TItem,TKey,TContext](IMemoryCache`1 cache, TKey key, TContext context, Func`3 factory)
         at LinqToDB.Mapping.MappingSchema.GetEntityDescriptor(Type type)
         at LinqToDB.Linq.Table`1.InitTable(IDataContext dataContext, Expression expression)
         at LinqToDB.Linq.Table`1..ctor(IDataContext dataContext)
         at LinqToDB.DataExtensions.GetTable[T](IDataContext dataContext)
```

**Comment by MaceWindu** [comment]
@sdanyliv
