### ISSUE TITLE
"Login failed for user" - exception in background in first use of `CreateLinqToDbConnection`

### ISSUE THREAD

**Issue by djfoxer** [linq2db/linq2db.EntityFrameworkCore#292]
Hi, I get mystery error when I use linq2db.EFCore. ApplicationInsights reports error in connection but error doesn't throw out, only ApplicationInsights catch it and reports.

When I try to create new linq2dbContext from existing Ef Core context by `CreateLinqToDbConnection` (Azure SQL)
```csharp
// uing DbContext
using (var dc = ctx.CreateLinqToDbConnection())
{
   // linq queries using linq2db extensions
}
```

I got exception in `CreateLinqToDbConnection` that doesn't appear, just AI catch it (so it looks like inner exception that doesn't throw but is catched by AI). EF Core queries connect without issues. Linq2Db queries too but this "background" exception occurs and it occurs only for first call of `CreateLinqToDbConnection` that uses linq2db. Only first time! 

```csharp
Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'my_user_name'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at LinqToDB.DataProvider.SqlServer.SqlServerProviderAdapter.SqlConnection.Open()
   at LinqToDB.DataProvider.SqlServer.SqlServerTools.ProviderDetector(IConnectionStringSettings css, String connectionString)
Error Number:18456,State:1,Class:14
```

**Comment by MaceWindu** [comment]
`SqlServerTools.ProviderDetector` creates connection to sql server to detect sql server version(dialect) to use and currently (in v4) it uses only connection string.
I suspect you use token-based auth, which is not used from provider detector code.

You can set `SqlServerTools.AutoDetectProvider = false;` for now (in v5 it will change)

@sdanyliv, could you add how user can specify required sql server version manually?

**Comment by djfoxer** [comment]
Can I provide sql server version by connection string?

**Comment by sdanyliv** [comment]
Currently we always autodetect version.
Try to create the following class:
```cs
public class MyImplementation : LinqToDBForEFToolsImplDefault
{
    protected override IDataProvider CreateSqlServerProvider(SqlServerVersion version, string? connectionString)
    {
        return DataProvider.SqlServer.SqlServerTools.GetDataProvider(version, SqlServerProvider.MicrosoftDataSqlClient);
    }
}
```    
And somewhere on startup call the following code ONCE per application:
```cs
MyImplementation.SqlServerDefaultVersion = SqlServerVersion.v2012; // set desired version
LinqToDBForEFTools.Implementation = new MyImplementation();        // replace current tools implementation
```

**Comment by djfoxer** [comment]
@MaceWindu @sdanyliv thank you for yours solutions. What will happen if I set AutoDetecProvider to false? I quick check it and exception go away. But could it break something?

**Comment by MaceWindu** [comment]
As it doesn't work for you anyways - it will just disable connection attempt and use SQL Server 2008 dialect (same as with exception)

**Comment by djfoxer** [comment]
@MaceWindu It's funny because it works, just with default values probably (Exception doesn't crash the app, I can only see error in inner AI logs and DB logs).

**Comment by MaceWindu** [comment]
BEcause exception is catched and default dialect used

**Comment by djfoxer** [comment]
@MaceWindu Ok. That's great. Thank you for your help.

**Comment by orty** [comment]
Hi,
I am experiencing quite the same behavior. I enabled LinqToDb globally in my startup, right where I build my `DbContext` and `UnitOfWork` (both transitent) using a Factory.

I have recurrent calls to my cache layer (managed in db) in which I call `.Delete` on an `IQueryable` representing the expired cache values.

As the library attempts a  connection and it is first rejected each time (with a 18456 error - password empty), Azure ends up considering the serveur hosting my application as a threat and the DoS guard blacklists its IP for a short period of time (within which no calls to db even using the standard EF layer manage to go through, eventually crashing the app itself).

I managed to debug through the connection opening process occurring within the library and it seemed to me that LinqToDb tries to retrieve the connection string from the initialized EF context, in which the password is redacted once the connection has been opened.
I cannot rely on `Persist Security Info=true` as a workaround. Do I have to implement the same thing you advised @djfoxer ?
Many thanks.

**Comment by MaceWindu** [comment]
With new release you can specify dialect explicitly in options:
```cs
builder.AddCustomOptions(o => o.UseSqlServer("unused", SqlServerVersion.v2022));
```

note that linq2db 5.0.0  contains bug, which will be solved in next release so you need to pass fake connection string parameter. After fix released you can do it like that:

```cs
builder.AddCustomOptions(o => o.UseSqlServer(SqlServerVersion.v2022));
```
