### ISSUE TITLE
Linq2db query working for FirstOrDefaultAsync but same query failing on ToListAsync?

### ISSUE THREAD

**Issue by aloksharma1** [linq2db/linq2db.EntityFrameworkCore#296]
Hello guys,

i updated to new linq2db version 4.4.1 and this weird issue popped up on my already working project, i have a task which fetches complex data of related tables and normalize it for faster access in sql.
this was working with previous version, i have confirmed the issue only happens on calling `tolist` otherwise its working fine, also its happening when it calls same repository subquery for 2 columns, here is the code with issue:

```
var blogQuery = await _blogPostRepository.NoTrackingQuery()
                   .Where(x => x.IsActive == true &&
                   (x.RecordStatus == RecordStatus.Published || x.RecordStatus == RecordStatus.ScheduledPublished) &&
                    (!_NormalizedPostRepository.NoTrackingQuery().Where(nblogs => nblogs.SiteId == x.SiteId).Select(nblogs => nblogs.BlogId).Contains(x.Id) ||
                    x.DateModified > _NormalizedPostRepository.NoTrackingQuery().Where(nblogs => nblogs.SiteId == x.SiteId && nblogs.BlogId == x.Id).Select(nblogs => nblogs.DateModified).FirstOrDefault()))
                   .Select(x => new BlogPostDTO
                   {                       
                       blogAuthor = _blogAuthorRepository.NoTrackingQuery().Where(a => a.IsActive == true && a.SiteId == x.SiteId && a.Id == x.AuthorId).Select(a =>
                               new BlogAuthorDTO
                               {
                                   Id = a.Id,
                                   AuthorImage = _imageRepository.NoTrackingQuery()
                                               .Where(pi => pi.Id == a.ProfileImageId).OrderBy(pi => pi.SortOrder)
                                               .Select(pi => new BlogImagesDTO
                                               {
                                                   ImagePath = pi.ImagePath,
                                                   ImageAltText = pi.ImageAltText,
                                                   SortOrder = pi.SortOrder,
                                                   Id = pi.Id
                                               }).FirstOrDefault(),
                                   BioSummary = a.BioSummary,
                                   AuthorProfile = _userRepository.NoTrackingQuery().FirstOrDefault(ap => ap.Id == a.UserId),
                                   Links = a.Links,
                                   UserStatus = a.UserStatus,
                                   PenName = a.PenName,
                                   PenSlug = a.PenSlug,
                                   AuthorPageSlug = _pageRepository.NoTrackingQuery().Where(p => p.Id == a.BioPageId && p.IsActive == true).Select(p => p.PageSlugUrl).FirstOrDefault()
                               }).FirstOrDefault(),
                       blogEditor = _blogAuthorRepository.NoTrackingQuery().Where(a => a.IsActive == true && a.SiteId == x.SiteId && a.Id == x.EditorAuthorId).Select(a =>
                                new BlogEditorDTO
                                {
                                    Id = a.Id,
                                    AuthorImage = _imageRepository.NoTrackingQuery()
                                                .Where(pi => pi.Id == a.ProfileImageId).OrderBy(pi => pi.SortOrder)
                                                .Select(pi => new BlogImagesDTO
                                                {
                                                    ImagePath = pi.ImagePath,
                                                    ImageAltText = pi.ImageAltText,
                                                    SortOrder = pi.SortOrder,
                                                    Id = pi.Id
                                                }).FirstOrDefault(),
                                    BioSummary = a.BioSummary,
                                    AuthorProfile = _userRepository.NoTrackingQuery().FirstOrDefault(ap => ap.Id == a.UserId),
                                    Links = a.Links,
                                    UserStatus = a.UserStatus,
                                    PenName = a.PenName,
                                    PenSlug = a.PenSlug,
                                    AuthorPageSlug = _pageRepository.NoTrackingQuery().Where(p => p.Id == a.BioPageId && p.IsActive == true).Select(p => p.PageSlugUrl).FirstOrDefault()
                                }).FirstOrDefault(),
                      // removed non-trivial code from query
                   }).AsSubQuery().ToLinqToDB().ToListAsyncLinqToDB();
```

in above i have removed additional columns, I traced the error by commenting and uncommenting each column field to make sure this is where the error was happening when calling `ToListAsyncLinqToDB` tried with/without .AsSubQuery() too without success.

As you can see only when their is a repeat of `_blogAuthorRepository` its giving me error, following is the stack trace and error message :
` Value cannot be null. (Parameter 'key')`
Stack trace

```
    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.AddOrUpdate(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsDataConnection.LinqToDB.Interceptors.IEntityServiceInterceptor.EntityCreated(EntityCreatedEventData eventData, Object entity)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.OnEntityCreated(IDataContext context, Object entity, TableOptions tableOptions, String tableName, String schemaName, String databaseName, String serverName)
   at lambda_method1503(Closure , IQueryRunner , DbDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, DbDataReader dataReader, ReaderMapperInfo& mapperInfo)
   at LinqToDB.Linq.QueryRunner.AsyncEnumeratorImpl`1.MoveNextAsync()
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+MoveNext()
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+MoveNext()
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
```

i am using the following:
1. sql server 2019
2. linq2db 4.4.1
3. ef core 5.0.17

**Comment by sdanyliv** [comment]
On which property it fails?

**Comment by aloksharma1** [comment]
> On which property it fails?

i have just edited my answer with additional information

**Comment by sdanyliv** [comment]
Can you put `AsNoTracking()` before `.AsNoTracking().ToListAsyncLinqToDB();`?

**Comment by aloksharma1** [comment]
this wont work in my design my irepository pattern gives a IQueryable on .AsNoTracking() my where condition depends on it.

**Comment by aloksharma1** [comment]
as i said in my issue `.AsSubQuery().ToLinqToDB().FirstOrDefaultAsyncLinqToDB()` works but if i change it to `ToListAsyncLinqToDB()` i am getting the above error.

**Comment by sdanyliv** [comment]
Strange. Try to disable it `LinqToDBForEFTools.EnableChangeTracker = false` somewhere on startup.

**Comment by sdanyliv** [comment]
It is just global flag. Set it somewhere.

**Comment by sdanyliv** [comment]
What to check? With this flag queries with linq2db no longer registered in change tracker. I'll check later what happened.

**Comment by aloksharma1** [comment]
i meant in my code, do i need to put this global value false everywhere i am running a complex query with ToList?

**Comment by sdanyliv** [comment]
No. Just do it once per application.

**Comment by MaceWindu** [comment]
Fix released
