### ISSUE TITLE
Support Microsoft SQLite Provider

### ISSUE THREAD

**Issue by QianMoXi** [linq2db/linq2db.EntityFrameworkCore#343]
Register:
`
optionsBuilder.UseLinqToDB(x => x.AddCustomOptions(o => o.UseSQLiteMicrosoft()))
`

When creating a connection, will throw an exception:
`
dbContext.CreateLinqToDBConnection()
`

```
LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsException : Can not instantiate data provider 'SQLite.MS'.
at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.CreateLinqToDBDataProvider(EFProviderInfo providerInfo, LinqToDBProviderInfo provInfo, EFConnectionInfo connectionInfo)
at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.<>c__DisplayClass4_0.<GetDataProvider>b__0(ProviderKey k)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.GetDataProvider(DataOptions options, EFProviderInfo providerInfo, EFConnectionInfo connectionInfo)
at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.GetDataProvider(DataOptions options, EFProviderInfo info, EFConnectionInfo connectionInfo)
at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.CreateLinqToDBConnection(DbContext context, IDbContextTransaction transaction)
```

Is this provider not supported or did you forget to add it?

https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/44de54e460309d3790a8eba8fc3375276201c93f/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs#L181-L182

**Comment by MaceWindu** [comment]
There is no need to specify exact provider for sqlite, but agree that we should accept specific name too
