### ISSUE TITLE
Getting error "ORA-00928" when trying to context.BulkCopy

### ISSUE THREAD

**Issue by lhmiranda** [linq2db/linq2db.EntityFrameworkCore#67]
Hey!

I just discovered linq2db and linq2db.EntityFramwrokCore while searching for a Bulk Insert option that would work with EF Core 3.1 and Oracle.
At first I was a bit skeptical of it being so simple to work. Now I think I may be missing something, because it's not working for me.

Ok, so I have a collection of <FlatConsult> entity that I need to upsert into my Oracle (**19c**) database. This is the code:
```c#
LinqToDBForEFTools.Initialize();
List<FlatConsult> data = GetData();
dwDb.BulkCopy(new BulkCopyOptions 
{ 
    BulkCopyType = OracleTools.DefaultBulkCopyType, 
    TableName = "ST.\"FlatConsults\"" 
}, data);
```
I had to specify the table otherwise I would get a “ORA-00942: table or view does not exist” error. But now I keep getting a "ORA-00928: missing SELECT keyword" error.
I even added linq2db.Oracle.Managed to see if it would help, but no success. I'm probably missing some more configuration, but I couldn't find any help on it.

And thank you for your work!

**Comment by sdanyliv** [comment]
I think problem here that you are trying to escape table name. Linq2db will do that automatically.
```cs
dwDb.BulkCopy(new BulkCopyOptions 
{ 
    BulkCopyType = OracleTools.DefaultBulkCopyType, 
    TableName = "FlatConsults",
    SchemaName = "ST"
}, data);
```
You do not have to specify these names if it is regular EF Model.

**Comment by lhmiranda** [comment]
I tried doing the way you recommended but it returns the same error that I get if I don't specify the table name: 
Oracle - ORA-00942: table or view does not exist.

**Comment by sdanyliv** [comment]
If in your EF Core application specified logging, you should see SQL sent to Oracle. Could you please post it?

**Comment by sdanyliv** [comment]
Anyway, check permissions. It is usual Oracle error.

**Comment by lhmiranda** [comment]
I forgot to mention that no SQL commands are logged when I get this errors. I get SQL statements in logs from LINQ queries but not from context.BulkCopy. I only get the exception log.

**Comment by sdanyliv** [comment]
Logging should work if you specify `optionsBuilder.UseLoggerFactory`

**Comment by lhmiranda** [comment]
Logs are working, I just don't get any SQL logs when I run ctx.BulkCopy().

**Comment by lhmiranda** [comment]
I had to use ``DataConnection.TurnTraceSwitchOn();`` but now SQL logs are shown:

```
info: LinqToDB[1]
      BeforeExecute
      --  Oracle Oracle11

      INSERT ALL
        INTO "ST."FlatConsults"" (Day, RetailerId, RetailerTradingName, RetailerDocument, SaleCountCash, SaleCountCard, ConsultCountCash, ConsultCountCard) VALUES (TO_TIMESTAMP('2020-09-13 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'),58934,'Retailer 339','325057315',402,297,537,675)
        INTO "ST."FlatConsults"" (Day, RetailerId, RetailerTradingName, RetailerDocument, SaleCountCash, SaleCountCard, ConsultCountCash, ConsultCountCard) VALUES (TO_TIMESTAMP('2020-09-16 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'),94179,'Retailer 38','382891318',441,385,535,480)
        INTO "ST."FlatConsults"" (Day, RetailerId, RetailerTradingName, RetailerDocument, SaleCountCash, SaleCountCard, ConsultCountCash, ConsultCountCard) VALUES (TO_TIMESTAMP('2020-09-05 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'),15545,'Retailer 593','464420620',959,165,232,791)
        INTO "ST."FlatConsults"" (Day, RetailerId, RetailerTradingName, RetailerDocument, SaleCountCash, SaleCountCard, ConsultCountCash, ConsultCountCard) VALUES (TO_TIMESTAMP('2020-08-18 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'),67795,'Retailer 429','618368830',433,197,851,766)
        INTO "ST."FlatConsults"" (Day, RetailerId, RetailerTradingName, RetailerDocument, SaleCountCash, SaleCountCard, ConsultCountCash, ConsultCountCard) VALUES (TO_TIMESTAMP('2020-08-27 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'),21638,'Retailer 653','194960673',955,363,817,141)
        INTO "ST."FlatConsults"" (Day, RetailerId, RetailerTradingName, RetailerDocument, SaleCountCash, SaleCountCard, ConsultCountCash, ConsultCountCard) VALUES (TO_TIMESTAMP('2020-08-23 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'),71157,'Retailer 543','431510080',69,440,772,78)
      SELECT * FROM d
```ual

fail: LinqToDB[2]
      Error
      Exception: Oracle.ManagedDataAccess.Client.OracleException
      Message  : ORA-00928: palavra-chave SELECT não encontrada
         at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
         at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
         at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
         at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)
         at LinqToDB.Data.DataConnection.ExecuteNonQuery()

**Comment by sdanyliv** [comment]
Looks like Oracle have broken backward compatibility and we have to correct BulkCopy SQL for 19-th dialect.

**Comment by sdanyliv** [comment]
`"ST."FlatConsults""` - something strange in this name.

**Comment by Shane32** [comment]
@lhmiranda  Were these logs taken with your original code (`TableName = "ST.\"FlatConsults\"" `) or with the suggested revision (`TableName = "FlatConsults", SchemaName = "ST"`) ?

**Comment by lhmiranda** [comment]
@Shane32 
1. ``TableName = "ST.\"FlatConsults\""`` yields: ``...INTO "ST."FlatConsults"" (...``
2. ``TableName = "FlatConsults"`` yields: ``...INTO FlatConsults (...``
3. ``TableName = "FlatConsults", SchemaName = "ST"`` yields: ``...INTO ST.FlatConsults (...``
4. Not specifying `TableName` and `SchemaName` yields ``...INTO FlatConsults (...`` (same as **2**)
5. ``SchemaName = "ST"`` yields: ``...INTO ST.FlatConsults (...`` (same as **3**)

None of which is accepted. I should be: ``...INTO ST."FlatConsults" (...``.

**Comment by sdanyliv** [comment]
@lhmiranda, maybe you have specification link about this escaping and we will update library for next release  which is planned on this Thursday.

**Comment by Shane32** [comment]
I don't have Oracle, but I found this link:
* https://docs.oracle.com/database/121/SQLRF/sql_elements008.htm#SQLRF51129

Of particular interest: (added emphasis)

> A quoted identifier begins and ends with double quotation marks ("). **If you name a schema object using a quoted identifier, then you must use the double quotation marks whenever you refer to that object.**

So it would seem that we would need to support table names in the format of `"name"` in addition to `name`, and that it should not add additional escaping.  Also noteworthy:

> Nonquoted identifiers can contain only alphanumeric characters from your database character set and the underscore (_), dollar sign ($), and pound sign (#). Database links can also contain periods (.) and "at" signs (@).

> Quoted identifiers can contain any characters and punctuations marks as well as spaces. **However, neither quoted nor nonquoted identifiers can contain double quotation marks or the null character (\0).**

Perhaps it should follow this pseudocode:
1. If matches regex `^\"[^\"]*\"$` then use as-is (quoted identifier)
2. If contains `\"` then throw exception
3. If matches regex `[^a-zA-Z_$@]` then assume unquoted identifier
4. Otherwise assume quoted identifier

Sorry, I don't have Oracle to do testing with.

**Comment by lhmiranda** [comment]
I really don't have a link for it. I learned it while using OCI's (Oracle Cloud Infrastructure) SQL Developer Web.
I tried the standard "SELECT * FROM FlatConsults" and it didn't worked. Then I dragged the table from the tables list into the query area it let me pick a "select data" option and then filled the query test with this:
![image](https://user-images.githubusercontent.com/522711/95266264-34e3bc00-0809-11eb-9a22-e75a395e8298.png)

**Comment by Shane32** [comment]
Perhaps there should also be a global or connection-specific Oracle flag to escape all object names, replacing steps 3 & 4 of the above with the following:

3. Assume quoted identifier and add quotes

**Comment by lhmiranda** [comment]
Look at EF Core queries in the log, it does uses quotes with table names when running queries, but it does not uses the schema name in front of it:

```c#
var consults = await db.FlatConsults.OrderByDescending(o => o.Day).Take(10).ToListAsync();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (214ms) [Parameters=[:p_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='0']
      SELECT "f"."Day", "f"."RetailerId", "f"."ConsultCountCard", "f"."ConsultCountCash", "f"."RetailerDocument", "f"."RetailerTradingName", "f"."SaleCountCard", "f"."SaleCountCash"
      FROM "FlatConsults" "f"
      ORDER BY "f"."Day" DESC
      FETCH FIRST :p_0 ROWS ONLY
```

**Comment by sdanyliv** [comment]
I assume this should also fail?
```cs
var consults = await db.FlatConsults.OrderByDescending(o => o.Day).Take(10).ToLinqToDB().ToListAsyncLinqToDB();
```

**Comment by lhmiranda** [comment]
Yep, same problem:

```c#
info: LinqToDB[1]
      BeforeExecute
      --  Oracle Oracle11 (asynchronously)
      DECLARE @take Int32
      SET     @take = 10

      SELECT
        t2.Day_1,
        t2.RetailerId,
        t2.RetailerTradingName,
        t2.RetailerDocument,
        t2.SaleCountCash,
        t2.SaleCountCard,
        t2.ConsultCountCash,
        t2.ConsultCountCard
      FROM
        (
                SELECT
                        t1.Day as Day_1,
                        t1.RetailerId,
                        t1.RetailerTradingName,
                        t1.RetailerDocument,
                        t1.SaleCountCash,
                        t1.SaleCountCard,
                        t1.ConsultCountCash,
                        t1.ConsultCountCard
                FROM
                        FlatConsults t1
                ORDER BY
                        t1.Day DESC
        ) t2
      WHERE
        ROWNUM <= :take

fail: LinqToDB[2]
      Error
      Exception: Oracle.ManagedDataAccess.Client.OracleException
      Message  : ORA-00942: table or view does not exist
         at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
         at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
         at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
         at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
         at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
      --- End of stack trace from previous location where exception was thrown ---
         at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
```

**Comment by MaceWindu** [comment]
Could you set
```cs
OracleTools.DontEscapeLowercaseIdentifiers = false;
```
option?
I wonder why we have it set to true by default.

**Comment by lhmiranda** [comment]
It might solve this. It actually states in it's description that it should be set to false. I'll test it and report back shortly.
