### ISSUE TITLE
about OrderByDescending(m => m.RechargeDate).Skip(10).Take(10)

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db.EntityFrameworkCore#7]
i use sqlsever 2008 , it's not has OFFSET keyword.
so how to use rownumber

**Comment by quan01994** [comment]
I can't reproduce the error. ：）

**Comment by quan01994** [comment]
If I come across this problem again，i will reopen this issue

**Comment by sdanyliv** [comment]
Just for information, linq2db supports all  T-SQL dialects staring from SQL Server 2000

**Comment by quan01994** [comment]
````
     var qry = from memberApply in Db.MemberApply
                          from branch in Db.BranchInfo
                          where branch.BranchCode == memberApply.BranchCode
                                && branch.BranchId == id
                                && memberApply.HandleStatus == 1
                          from wxAttention in Db.WxAttention.LeftJoin(wx => wx.WxopenId == memberApply.WxopenId)
                          select new MemberApplyListOutput
                          {
                              ApplyBirthday = memberApply.ApplyBirthday,
                              Wxavatar = wxAttention.Wxavatar,
                              ApplyId = memberApply.ApplyId,
                              ApplyName = memberApply.ApplyName,
                              ApplySex = memberApply.ApplySex,
                              ApplyTelPhone = memberApply.ApplyTelPhone,
                              BranchName = memberApply.BranchName,
                              CreateTime = memberApply.CreateTime,
                              OpenCardEmpName = memberApply.OpenCardEmpName,
                          };

                result.Count = await qry.ToLinqToDB().CountAsync();
                result.Data = await qry.OrderByDescending(m => m.CreateTime).Skip((page - 1) * pageSize).Take(pageSize).ToLinqToDB().ToListAsync();
````

i use sqlserver 2003

mydb context 

````
  public HYWCRMContext(string connectionString) : base(new DbContextOptionsBuilder<HYWCRMContext>()
            .UseSqlServer(connectionString, b => b.UseRowNumberForPaging()).Options)
        {

        }
````

throw this exception

````
2018-08-13 11:32:59.1905|-2146232060|Hyw.Api.Empl.Infrastructure.Filters.HttpGlobalExceptionFilter|ERROR|'OFFSET' 附近有语法错误。
在 FETCH 语句中选项 NEXT 的用法无效。 System.Data.SqlClient.SqlException (0x80131904): 'OFFSET' 附近有语法错误。
在 FETCH 语句中选项 NEXT 的用法无效。
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.Async.cs:line 165
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 471
   at LinqToDB.Linq.QueryRunner.AsyncEnumeratorImpl`1.MoveNext(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 441
   at System.Linq.AsyncEnumerable.Aggregate_[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\AsyncExtensions.cs:line 149
   at Hyw.QueryServices.EFCore.MemberApplyQuery.GetListByIdAndTypeAsync(Int32 id, Int32 type, Int32 page, Int32 pageSize) in D:\VsProjects\Hyw2\src\Hyw.QueryServices.EFCore\MemberApplyQuery.cs:line 85
   at Hyw.Api.Empl.Controllers.MemberApplyController.Get(BaseModel model, PageModel page) in D:\VsProjects\Hyw2\hosts\Hyw.Api.Empl\Controllers\MemberApplyController.cs:line 47
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
ClientConnectionId:c929e8de-6826-4ad8-8266-caaab0e55729
Error Number:102,State:1,Class:15
````

**Comment by sdanyliv** [comment]
Show me the EF logs. And please translate exception messages to english. I can’t do that myself when you post screenshots.
linq2db - should log executed queries.

**Comment by sdanyliv** [comment]
Looks like SQL Server version auto-detection fails. 
Could you please send result of this query:
```sql
Select @@version
```

**Comment by MaceWindu** [comment]
@sdanyliv, FIY, autodetection should use compatibility level of database, not @@version. We had this change in linq2db for 2.2

**Comment by quan01994** [comment]
Select @@version

Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)   Apr  2 2010 15:48:46   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

**Comment by sdanyliv** [comment]
And this query also. Run this query in your database context.
```sql
SELECT compatibility_level FROM sys.databases WHERE name = db_name()
```
And just for clarification. Do you cahnge compatibility level during application execution?

**Comment by quan01994** [comment]
My program is now running normally，
Sometimes this problem occurs，

**Comment by sdanyliv** [comment]
Linq2db logs which sql dialect are used. Analyse that and please send result from compatibility level query.

**Comment by quan01994** [comment]
how to get this logger

**Comment by sdanyliv** [comment]
If you are using EF Core, it has logging. Our integration uses the same mechanism.
https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging

**Comment by quan01994** [comment]
Now I can't reproduce the problem.

**Comment by quan01994** [comment]
![image](https://user-images.githubusercontent.com/20533465/44507747-4972a200-a6de-11e8-8925-38d5800a34b1.png)
but i'm 2008

**Comment by quan01994** [comment]
When I restart, it may get better
![image](https://user-images.githubusercontent.com/20533465/44508450-e3d3e500-a6e0-11e8-833c-720a44b79e8e.png)
how abdout set dbconfig in startup.

**Comment by sdanyliv** [comment]
I'm interested in this information:
```sql
SELECT compatibility_level FROM sys.databases WHERE name = db_name()
```
Also as workaround you can override class `LinqToDBForEFToolsImplDefault` and implement method `CreateSqlServerProvider` with the following code:
```cs
protected override IDataProvider CreateSqlServerProvider(SqlServerVersion version, string connectionString)
{
   return new SqlServerDataProvider(ProviderName.SqlServer2008, SqlServerVersion.v2008);
}
```
And assign on startup this implementation:
```cs
LinqToDBForEFTools.Implementation = new MyImplementation();
```

**Comment by quan01994** [comment]
query this in dbcontext?
SELECT compatibility_level FROM sys.databases WHERE name = db_name()

**Comment by sdanyliv** [comment]
Looks like version autodetection needs to be improved, 
Strange but `100` is correct value for SQL Server 2008, and we process it accordingly.
